### PR TITLE
Rest engine

### PR DESCRIPTION
**Pull request by akshaisarma**
Not ready yet. Code is relatively complete. Tests in progress.

### CODE REVIEW

**Comment by akshaisarma** [comment]
Ready for review. Added tests and samples. Had to force a JDK minor version because of https://github.com/travis-ci/travis-ci/issues/3259

I'll give it another once over tomorrow and see if there's any cleanups left, but open for comments.

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by akshaisarma** [comment]
The build broke because the jdk8 download failed. Travis apparently doesn't fail the build then. There is an issue for this: https://github.com/travis-ci/travis-ci/issues/5077

I don't feel comfortable adding YET another travis workaround. Let me retry to see if it passes.

**Comment by joshwalters** [comment]
:+1: Looks good to me!

Should we add a little more documentation in the readme about how this works, or just use the unit tests / fake scripts to provide that?

**Comment by akshaisarma** [comment]
Maybe a little more documentation could be useful. I'll add that.

**Comment by akshaisarma** [comment]
I added some more documentation.

**Pull request merged**
