### PR TITLE
Fixing hive null type handling. Adding parameter support to asserts

### PR DESCRIPTION
**Pull request by akshaisarma**

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by akshaisarma** [comment]
This fixes an issue where null values occur in the data for Hive. 
Reference: http://grepcode.com/file/repo1.maven.org/maven2/org.apache.hive/hive-jdbc/0.13.1/org/apache/hive/jdbc/HiveBaseResultSet.java

Also implements #24

**Comment by joshwalters** [comment]
👍  Looks good. There is a unit test failure in REST JSONTest though.

**Comment by akshaisarma** [comment]
I think it's because of a JDK minor version. It looks like Nashorn started parsing some Longs as Doubles. It passes fine on 1.8.0_74 but fails on 1.8.0_101. I'll look at it some more.

**Comment by akshaisarma** [comment]
I made it not distinguish between Longs and Doubles and take all non-Integers as Double values.  This works in both JDKs.

**Pull request merged**
